var cards = [
    { id: 5, rarity: ['r', 'rp', 'sr', 'ssr'] },
    { id: 15, rarity: ['r', 'rp'] },
    { id: 17, rarity: ['n', 'np'] },
    { id: 21, rarity: ['n', 'np'] },
    { id: 23, rarity: ['r', 'rp'] },
    { id: 29, rarity: ['n', 'np', 'ssr'] },
    { id: 35, rarity: ['n', 'np'] },
    { id: 39, rarity: ['r', 'rp', 'ssr'] },
    { id: 50, rarity: ['r', 'rp'] },
    { id: 54, rarity: ['r', 'rp'] },
    { id: 59, rarity: ['sr', 'ssr'] },
    { id: 67, rarity: ['sr', 'ssr'] },
    { id: 73, rarity: ['r', 'rp'] },
    { id: 79, rarity: ['n', 'np'] },
    { id: 83, rarity: ['r', 'rp'] },
    { id: 87, rarity: ['r', 'rp', 'sr', 'ssr'] },
    { id: 103, rarity: ['r', 'rp'] },
    { id: 108, rarity: ['np', 'r', 'rp'] },
    { id: 112, rarity: ['n', 'np'] },
    { id: 119, rarity: ['r', 'rp', 'sr', 'ssr'] },
    { id: 123, rarity: ['sr', 'ssr'] },
    { id: 125, rarity: ['sr', 'ssr'] },
    { id: 127, rarity: ['r', 'rp'] },
    { id: 131, rarity: ['n', 'np'] },
    { id: 141, rarity: ['n', 'np'] },
    { id: 147, rarity: ['n', 'np'] },
    { id: 155, rarity: ['n', 'np'] },
    { id: 170, rarity: ['n', 'np'] },
    { id: 175, rarity: ['n', 'np', 'r', 'rp'] },
    { id: 208, rarity: ['ssr'] },
    { id: 215, rarity: ['n', 'np', 'r', 'rp'] },
    { id: 219, rarity: ['sr', 'ssr'] },
    { id: 225, rarity: ['n', 'np', 'sr', 'ssr'] },
    { id: 239, rarity: ['n', 'np'] },
    { id: 280, rarity: ['n', 'np', 'sr', 'ssr'] },
    { id: 284, rarity: ['n', 'np'] },
    { id: 298, rarity: ['n', 'np', 'sr', 'ssr'] },
    { id: 306, rarity: ['n', 'np', 'r', 'sr', 'ssr'] },
    { id: 312, rarity: ['r', 'rp', 'sr', 'ssr'] },
    { id: 316, rarity: ['r', 'rp'] },
    { id: 318, rarity: ['r', 'rp'] },
    { id: 328, rarity: ['n', 'np', 'r', 'rp'] },
    { id: 332, rarity: ['n', 'r', 'sr', 'ssr'] },
    { id: 336, rarity: ['n', 'np'] },
    { id: 342, rarity: ['r', 'rp'] },
    { id: 348, rarity: ['r', 'rp'] },
]